services:
  flower-shop:
    image: postgres:alpine
    container_name: flower-shop
    ports:
      - "6004:5432"
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: spring-2024